.TH FILETWM 1

.SH NAME
filetwm \- a palatable lean slice of window manager

.SH KEYBOARD SHORTCUTS
.RS
.TS
tab (@);
r l.
Keys@Action
_
Win+MouseMotion:@show bar
Win+Esc:@open launcher
Win+Control+Space:@open terminal
Win+Alt+Space:@move window
Win+Space:@resize window
Win+Backspace:@tile window
Win+Enter:@fullscreen window
Win+Alt+Enter:@pin window
Win+Shift+Enter:@raise window
Win+Up/Down:@switch window
Win(+Shift)+Tab:@switch window, and raise
Win+Left/Right:@switch workspace
Win+Shift+Left/Right:@switch workspace with window
Win+[1-9]:@switch workspace
Win+Shift+[1-9]:@move window to workspace
Win+Alt+[1-9]:@add window to workspace
Win+0:@add window to all workspaces
Win+F4:@close window
Win+Shift+F4:@sleep
Win+Shift+Ctrl+F4:@quit
.TE
.RE

.SH DESCRIPTION
filetwm is a minimalist window manager for X. It manages windows in tiled and
free floating layers, across virtual workspaces, with support for fullscreen
and pinned windows.
.P
In the tiling layer, windows are arranged into columns, and newly tiled windows
will create a new column. Column widths can be adjusted by resizing the top
window of each column, and moving windows will shift them to different
columns or move them to a different row position. The height of each window in
a column can adjusted by resizing. The final columns of the monitor, and the
final windows of each column, will be shrunk, if needed, to fit the
monitor area. Vertical monitors follow a similar tiling layout but are organised
so that the columns are arranged horizontally. In the floating layer, windows can be
resized and moved freely.
.P
In the floating layer, windows can be resized and moved freely. All windows
start out floating and can be switched between the tiled layer on demand.
.P
Window focus follows the mouse and clicks will raise a window. If any
floating window is raised, all floating windows will sit above tiled windows.
Fullscreen windows that are not raised will sit behind the tiled layer.
.P
There is a small status bar which contains a display of the virtual workspaces,
with the selected workspace highlighted, and a customisable status message.
.P
Windows have thin borders and indicate the focus state with a highlight color.

.SH USAGE
The primary control interface is intended to be via the keyboard shortcuts
detailed above, along with mouse control for window focus, click-to-raise,
using the inbuilt launcher, and all sizing movements, but additional mouse
controls are supported:

.RS
.TS
tab (@);
r l.
Trigger@Action
_
Left Click Selected Workspace:@open launcher
Left Click New Workspace:@show workspace
Right Click New Workspace:@relocate window
Left Click Status Pane:@open help
Left Click Top/Left Win-Edge:@move window
Left Click Bottom/Right Win-Edge:@resize window
.TE
.RE

.SS Inbuilt launcher
The inbuilt launcher will show a list of commands. Typing will filter the
command list, Left and Right Arrows will select from the listed commands,
Enter will launch the selected command, and Escape will exit the launcher.


.SH CUSTOMIZATION
.SS Config plugins
filetwm supports config plugins which can be installed to the system at
.B /etc/config/filetwmconf.so,
or for a user at
.B ~/.config/filetwmconf.so.

.RS
/* filetwmconf.c: Example source config file for filetwm's config plugin,
changing the status bar font size. Build and install config:

cc -shared -fPIC filetwmconf.c -o ~/.config/filetwmconf.so
*/

void config() { extern char *font; font = "monospace:bold:size=5"; }
.RE

See https://github.com/fuglaro/filet-wm#Configuration for further details.

.SS Background image
To custimise a background image, you must apply a background to the root
window. This can be done with a startup script or after launching. E.g:
.B feh --bg-tile ~/.config/background.jpg

.SS Status bar
The status bar can be updated by changing the window name of the X root window.
It can be set with the
.BR xsetroot (1)
command.

.SS Inbuilt launcher
The inbuilt launcher finds commands from the PATH environment variable.
Commands are listed in the order they are found, from each entry in PATH,
and in the directory listing order within each entry. Favorites should
be ordered as desired in a directory at the top of the PATH.

.SH SYNOPSIS
.B filetwm
